### ISSUE TITLE
[FEATURE] JOB Sytem

### ISSUE THREAD

**Issue by GhostV-Survival** [ChatDisabled/dc-casino#2]
A Jobsystem like qb-policejob.

**Comment by ChatDisabled** [comment]
@GhostLegionRP what would you expect this job to do in the casino though? They should handle what?

**Comment by GhostV-Survival** [comment]
> @GhostLegionRP what would you expect this job to do in the casino though? They should handle what?

@ChatDisabled 
A professional system that can receive and manage the deposits from the games of chance, so that the players can have a casino profession and, for example, manage a bar also the payment of the winnings should be able to work optionally on the income collected

**Comment by elkie1991gaming** [comment]
also could make a membership that expires 1 week irl would be cool if you dont have a membership then it will not allow you to use anything
