### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Steviithetv** [ChatDisabled/dc-casino#4]
I'm using qb-core and when sit on the machine to play it show me this error , how can I fix it please help!
![image](https://user-images.githubusercontent.com/111495951/216154733-605c241c-38a3-44c8-8f3b-0c5dd74e92f9.png)

**Comment by ChatDisabled** [comment]
Either update your core or use a different drawtext solution

**Comment by Steviithetv** [comment]
okay, thanks ! <3
